spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Product Service

server:
  port: 9788


---
spring:
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      jakarta:
        persistence.validation.mode: none
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://localhost:5432/stock_management"
    username: postgres
    password: 12345
